// Generated by CoffeeScript 1.9.3
(function() {
  var StockList, db, stockListTable;

  db = require('./DB');

  stockListTable = db.get('stocklist');

  StockList = {
    getNumberOfStocksWithName: function(stockname) {
      return stockListTable.count({
        stockname: stockname
      });
    }
  };

  module.exports = StockList;

}).call(this);
