// Generated by CoffeeScript 1.9.3
(function() {
  var app, bodyParser, db, express, logger, mongo, monk, routes, stock, stocklist;

  express = require('express');

  logger = require('morgan');

  bodyParser = require('body-parser');

  mongo = require('mongodb');

  monk = require('monk');

  db = monk('localhost:27017/StockApplication');

  routes = require('./routes/index');

  stocklist = require('./routes/stocklist');

  stock = require('./routes/stock');

  app = express();

  app.set('views', 'views');

  app.set('view engine', 'jade');

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(express["static"]('public'));

  app.use(function(req, res, next) {
    req.db = db;
    return next();
  });

  app.use(stocklist);

  app.use(stock);

  app.use(routes);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: {}
    });
  });

  module.exports = app;

}).call(this);
