// Generated by CoffeeScript 1.9.3
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('*', function(req, res, next) {
    res.render('index', {
      title: 'Stock Application'
    });
    return res.end();
  });

  module.exports = router;

}).call(this);
