// Generated by CoffeeScript 1.9.3
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/stocklist', function(req, res, next) {
    var collection, db;
    db = req.db;
    collection = db.get('stocklist');
    return collection.find({}, {
      sort: {
        stockname: 1
      }
    }, function(err, stocklist) {
      return res.render('stocklist', {
        title: 'Stock List',
        'stocklist': stocklist
      });
    });
  });

  router.post('/addstock', function(req, res, next) {
    var collection, db, stock;
    db = req.db;
    stock = req.body;
    stock.stockname = stock.stockname.toUpperCase();
    collection = db.get('stocklist');
    collection.count({
      'stockname': stock.stockname
    }).then(function(count) {
      if (count === 0) {
        if (!stock.number) {
          stock.number = 0;
        }
        if (!stock.acb) {
          stock.acb = 0;
        }
        return collection.insert(stock);
      }
    });
    return res.redirect('stocklist');
  });

  router.post('/deletestock', function(req, res, next) {
    var collection, db, stockname;
    db = req.db;
    stockname = req.body.stockname;
    collection = db.get('stocklist');
    return collection.remove({
      stockname: stockname
    }, function(err) {
      if (err) {
        res.send('There was a problem deleting the information to the database.');
      }
      return res.redirect('stocklist');
    });
  });

  module.exports = router;

}).call(this);
