// Generated by CoffeeScript 1.9.3
(function() {
  var controller, express, stockController, stockListControlller;

  express = require('express');

  controller = express.Router();

  stockListControlller = require('./stocklist');

  stockController = require('./stock');

  controller.use(stockListControlller);

  controller.use(stockController);

  controller.get('*', function(req, res) {
    return res.render('index', {
      title: 'Stock Application'
    });
  });

  module.exports = controller;

}).call(this);
