// Generated by CoffeeScript 1.9.3
(function() {
  var Entries, StockList, controller, express, stockController, stockListControlller;

  express = require('express');

  controller = express.Router();

  stockListControlller = require('./stocklist');

  stockController = require('./stock');

  Entries = require('../models/Entries');

  StockList = require('../models/StockList');

  controller.use(stockListControlller);

  controller.use(stockController);

  controller.get('/debug', function(req, res) {
    return StockList.getStockListOrdered().then(function(stocklist) {
      return Entries.getAllEntriesOrdered().then(function(entries) {
        return res.render('debug', {
          stocklist: stocklist,
          entries: entries
        });
      });
    });
  });

  controller.get('*', function(req, res) {
    return res.render('index', {
      title: 'Stock Application'
    });
  });

  module.exports = controller;

}).call(this);
